#!/usr/bin/env bun
/**
 * Renders the Homebrew formula (`emitsignal.rb`) for the tap repo from the
 * checksums produced by `build-binaries.ts`. CI pushes the output to
 * `emitsignal/homebrew-tap`.
 *
 * Usage:
 *   bun run scripts/render-formula.ts [--tag v1.0.0] [--out path/emitsignal.rb]
 *
 * Defaults: tag = `v<version from package.json>`, out = stdout.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import packageJson from '../package.json' with { type: 'json' };

const REPOSITORY = 'emitsignal/emitsignal';
const CHECKSUMS_PATH = join(import.meta.dir, '..', 'dist-bin', 'checksums.txt');

type PlatformKey = 'darwin-arm64' | 'darwin-x64' | 'linux-arm64' | 'linux-x64';

function argValue(flag: string): string | undefined {
    const index = process.argv.indexOf(flag);

    return index === -1 ? undefined : process.argv[index + 1];
}

function checksumFor(checksums: Record<string, string>, platform: PlatformKey): string {
    const fileName = `emitsignal-${platform}.tar.gz`;
    const digest = checksums[fileName];

    if (!digest) {
        throw new Error(`missing checksum for ${fileName} — run build-binaries.ts first`);
    }

    return digest;
}

async function main(): Promise<void> {
    const version = packageJson.version;
    const tag = argValue('--tag') ?? `v${version}`;
    const outputPath = argValue('--out');

    const checksums = await parseChecksums();
    const formula = renderFormula(tag, version, checksums);

    if (outputPath) {
        await writeFile(outputPath, formula);
        console.log(`wrote ${outputPath}`);
    } else {
        process.stdout.write(formula);
    }
}

async function parseChecksums(): Promise<Record<string, string>> {
    const contents = await readFile(CHECKSUMS_PATH, 'utf8');
    const checksums: Record<string, string> = {};

    for (const line of contents.split('\n')) {
        const match = line.match(/^([0-9a-f]{64})\s+(emitsignal-[a-z0-9-]+\.tar\.gz)$/);

        if (match) {
            checksums[match[2]!] = match[1]!;
        }
    }

    return checksums;
}

function releaseUrl(tag: string, platform: PlatformKey): string {
    return `https://github.com/${REPOSITORY}/releases/download/${tag}/emitsignal-${platform}.tar.gz`;
}

function renderFormula(tag: string, version: string, checksums: Record<string, string>): string {
    const block = (platform: PlatformKey): string =>
        `      url "${releaseUrl(tag, platform)}"\n      sha256 "${checksumFor(checksums, platform)}"`;

    return `# typed: false
# frozen_string_literal: true

# This file is generated by scripts/render-formula.ts — do not edit by hand.
class Emitsignal < Formula
  desc "Publish and stream signals from your terminal"
  homepage "https://emitsignal.com/cli"
  version "${version}"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
${block('darwin-arm64')}
    end
    on_intel do
${block('darwin-x64')}
    end
  end

  on_linux do
    on_arm do
${block('linux-arm64')}
    end
    on_intel do
${block('linux-x64')}
    end
  end

  def install
    bin.install "emitsignal"
    bin.install_symlink "emitsignal" => "es"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/emitsignal --version")
  end
end
`;
}

await main();
