#!/usr/bin/env bun
/**
 * Generates `src/data/changelog.generated.ts` from the repository-root CHANGELOG.md,
 * which release-please owns. Runs from the website's predev/prebuild/pretest hooks so
 * the public changelog page can never drift from the released changelog.
 *
 * Usage:
 *   bun run scripts/sync-changelog.ts
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const CHANGELOG_PATH = join(import.meta.dir, '..', '..', '..', 'CHANGELOG.md');
const OUTPUT_PATH = join(import.meta.dir, '..', 'src', 'data', 'changelog.generated.ts');

const VERSION_HEADING =
    /^##\s+(?:\[(?<linked>[^\]]+)\]\([^)]*\)|(?<plain>[^\s(]+))\s*\((?<date>[^)]+)\)\s*$/;
const SECTION_HEADING = /^###\s+(?<section>.+?)\s*$/;
const BULLET = /^[*-]\s+(?<item>.+?)\s*$/;

// eslint's perfectionist/sort-objects lints the generated module, so emit keys in order.
const SORTED_KEYS = ['added', 'date', 'fixed', 'improved', 'note', 'version'];

const SECTION_KEYS: Record<string, 'added' | 'fixed' | 'improved'> = {
    added: 'added',
    'bug fixes': 'fixed',
    features: 'added',
    fixed: 'fixed',
    improved: 'improved',
    'performance improvements': 'improved',
};

interface ChangeEntry {
    added?: string[];
    date: string;
    fixed?: string[];
    improved?: string[];
    note?: string;
    version: string;
}

/**
 * release-please appends a `([sha](commit-url))` reference to every bullet and bolds the
 * commit scope. The page renders plain text, so both would leak as literal markdown.
 */
function cleanMarkdown(text: string): string {
    return text
        .replace(/\s*\(\[[0-9a-f]{6,}\]\([^)]*\)\)\s*$/, '')
        .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
        .replace(/\*\*/g, '')
        .replace(/\\([\\`*_{}[\]()#+\-.!])/g, '$1')
        .trim();
}

async function main(): Promise<void> {
    const markdown = await readFile(CHANGELOG_PATH, 'utf8');
    const entries = parseChangelog(markdown);

    if (entries.length === 0) {
        throw new Error(`no releases parsed from ${CHANGELOG_PATH}`);
    }

    await mkdir(dirname(OUTPUT_PATH), { recursive: true });
    await writeFile(OUTPUT_PATH, renderModule(entries));

    console.log(`wrote ${entries.length} releases to ${OUTPUT_PATH}`);
}

function parseChangelog(markdown: string): ChangeEntry[] {
    const entries: ChangeEntry[] = [];

    let entry: ChangeEntry | undefined;
    let sectionKey: 'added' | 'fixed' | 'improved' | undefined;

    for (const line of markdown.split('\n')) {
        const versionMatch = VERSION_HEADING.exec(line);

        if (versionMatch?.groups) {
            const { date, linked, plain } = versionMatch.groups;

            entry = { date: date.trim(), version: (linked ?? plain).trim() };
            sectionKey = undefined;
            entries.push(entry);

            continue;
        }

        if (!entry) {
            continue;
        }

        const sectionMatch = SECTION_HEADING.exec(line);

        if (sectionMatch?.groups) {
            sectionKey = SECTION_KEYS[sectionMatch.groups.section.trim().toLowerCase()];

            continue;
        }

        const bulletMatch = BULLET.exec(line);

        if (bulletMatch?.groups && sectionKey) {
            const item = cleanMarkdown(bulletMatch.groups.item);

            if (item) {
                entry[sectionKey] = [...(entry[sectionKey] ?? []), item];
            }

            continue;
        }

        const paragraph = line.trim();

        if (paragraph && !sectionKey && !entry.note && !paragraph.startsWith('#')) {
            entry.note = cleanMarkdown(paragraph);
        }
    }

    return entries;
}

function renderModule(entries: ChangeEntry[]): string {
    return `// Generated by scripts/sync-changelog.ts from CHANGELOG.md — do not edit.

export interface ChangeEntry {
    added?: string[];
    date: string;
    fixed?: string[];
    improved?: string[];
    note?: string;
    version: string;
}

export const CHANGELOG_RELEASES: ChangeEntry[] = ${JSON.stringify(entries, SORTED_KEYS, 4)};
`;
}

await main();
