/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CliRouteImport } from './routes/cli'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppPublishRouteImport } from './routes/app/publish'
import { Route as AppKeysRouteImport } from './routes/app/keys'
import { Route as AppChannelsRouteImport } from './routes/app/channels'
import { Route as AppWebhooksIndexRouteImport } from './routes/app/webhooks/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppInboxIndexRouteImport } from './routes/app/inbox/index'
import { Route as AppWebhooksNewRouteImport } from './routes/app/webhooks/new'
import { Route as AppWebhooksWebhookIdRouteImport } from './routes/app/webhooks/$webhookId'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsBillingRouteImport } from './routes/app/settings/billing'
import { Route as AppSettingsAdvancedRouteImport } from './routes/app/settings/advanced'
import { Route as AppSettingsAccountRouteImport } from './routes/app/settings/account'
import { Route as AppInboxMessageIdRouteImport } from './routes/app/inbox/$messageId'
import { Route as AppWebhooksWebhookIdEditRouteImport } from './routes/app/webhooks/$webhookId.edit'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishRoute = AppPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksIndexRoute = AppWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksNewRoute = AppWebhooksNewRouteImport.update({
  id: '/webhooks/new',
  path: '/webhooks/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksWebhookIdRoute = AppWebhooksWebhookIdRouteImport.update({
  id: '/webhooks/$webhookId',
  path: '/webhooks/$webhookId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAdvancedRoute = AppSettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppInboxMessageIdRoute = AppInboxMessageIdRouteImport.update({
  id: '/inbox/$messageId',
  path: '/inbox/$messageId',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksWebhookIdEditRoute =
  AppWebhooksWebhookIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppWebhooksWebhookIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/mobile': typeof MobileRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/keys': typeof AppKeysRoute
  '/app/publish': typeof AppPublishRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/inbox/$messageId': typeof AppInboxMessageIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/advanced': typeof AppSettingsAdvancedRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/webhooks/$webhookId': typeof AppWebhooksWebhookIdRouteWithChildren
  '/app/webhooks/new': typeof AppWebhooksNewRoute
  '/app/inbox/': typeof AppInboxIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/webhooks/': typeof AppWebhooksIndexRoute
  '/app/webhooks/$webhookId/edit': typeof AppWebhooksWebhookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/changelog': typeof ChangelogRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/mobile': typeof MobileRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/keys': typeof AppKeysRoute
  '/app/publish': typeof AppPublishRoute
  '/app': typeof AppIndexRoute
  '/app/inbox/$messageId': typeof AppInboxMessageIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/advanced': typeof AppSettingsAdvancedRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/webhooks/$webhookId': typeof AppWebhooksWebhookIdRouteWithChildren
  '/app/webhooks/new': typeof AppWebhooksNewRoute
  '/app/inbox': typeof AppInboxIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/webhooks': typeof AppWebhooksIndexRoute
  '/app/webhooks/$webhookId/edit': typeof AppWebhooksWebhookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/cli': typeof CliRoute
  '/dashboard': typeof DashboardRoute
  '/mobile': typeof MobileRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/keys': typeof AppKeysRoute
  '/app/publish': typeof AppPublishRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/inbox/$messageId': typeof AppInboxMessageIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/advanced': typeof AppSettingsAdvancedRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/webhooks/$webhookId': typeof AppWebhooksWebhookIdRouteWithChildren
  '/app/webhooks/new': typeof AppWebhooksNewRoute
  '/app/inbox/': typeof AppInboxIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/webhooks/': typeof AppWebhooksIndexRoute
  '/app/webhooks/$webhookId/edit': typeof AppWebhooksWebhookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/app'
    | '/changelog'
    | '/cli'
    | '/dashboard'
    | '/mobile'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/verify'
    | '/app/channels'
    | '/app/keys'
    | '/app/publish'
    | '/app/settings'
    | '/app/'
    | '/app/inbox/$messageId'
    | '/app/settings/account'
    | '/app/settings/advanced'
    | '/app/settings/billing'
    | '/app/settings/profile'
    | '/app/webhooks/$webhookId'
    | '/app/webhooks/new'
    | '/app/inbox/'
    | '/app/settings/'
    | '/app/webhooks/'
    | '/app/webhooks/$webhookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/changelog'
    | '/cli'
    | '/dashboard'
    | '/mobile'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/verify'
    | '/app/channels'
    | '/app/keys'
    | '/app/publish'
    | '/app'
    | '/app/inbox/$messageId'
    | '/app/settings/account'
    | '/app/settings/advanced'
    | '/app/settings/billing'
    | '/app/settings/profile'
    | '/app/webhooks/$webhookId'
    | '/app/webhooks/new'
    | '/app/inbox'
    | '/app/settings'
    | '/app/webhooks'
    | '/app/webhooks/$webhookId/edit'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/app'
    | '/changelog'
    | '/cli'
    | '/dashboard'
    | '/mobile'
    | '/onboarding'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/verify'
    | '/app/channels'
    | '/app/keys'
    | '/app/publish'
    | '/app/settings'
    | '/app/'
    | '/app/inbox/$messageId'
    | '/app/settings/account'
    | '/app/settings/advanced'
    | '/app/settings/billing'
    | '/app/settings/profile'
    | '/app/webhooks/$webhookId'
    | '/app/webhooks/new'
    | '/app/inbox/'
    | '/app/settings/'
    | '/app/webhooks/'
    | '/app/webhooks/$webhookId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  AppRoute: typeof AppRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  CliRoute: typeof CliRoute
  DashboardRoute: typeof DashboardRoute
  MobileRoute: typeof MobileRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish': {
      id: '/app/publish'
      path: '/publish'
      fullPath: '/app/publish'
      preLoaderRoute: typeof AppPublishRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/keys': {
      id: '/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/channels': {
      id: '/app/channels'
      path: '/channels'
      fullPath: '/app/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webhooks/': {
      id: '/app/webhooks/'
      path: '/webhooks'
      fullPath: '/app/webhooks/'
      preLoaderRoute: typeof AppWebhooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/inbox/': {
      id: '/app/inbox/'
      path: '/inbox'
      fullPath: '/app/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webhooks/new': {
      id: '/app/webhooks/new'
      path: '/webhooks/new'
      fullPath: '/app/webhooks/new'
      preLoaderRoute: typeof AppWebhooksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webhooks/$webhookId': {
      id: '/app/webhooks/$webhookId'
      path: '/webhooks/$webhookId'
      fullPath: '/app/webhooks/$webhookId'
      preLoaderRoute: typeof AppWebhooksWebhookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/advanced': {
      id: '/app/settings/advanced'
      path: '/advanced'
      fullPath: '/app/settings/advanced'
      preLoaderRoute: typeof AppSettingsAdvancedRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/account': {
      id: '/app/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/inbox/$messageId': {
      id: '/app/inbox/$messageId'
      path: '/inbox/$messageId'
      fullPath: '/app/inbox/$messageId'
      preLoaderRoute: typeof AppInboxMessageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webhooks/$webhookId/edit': {
      id: '/app/webhooks/$webhookId/edit'
      path: '/edit'
      fullPath: '/app/webhooks/$webhookId/edit'
      preLoaderRoute: typeof AppWebhooksWebhookIdEditRouteImport
      parentRoute: typeof AppWebhooksWebhookIdRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAdvancedRoute: typeof AppSettingsAdvancedRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAdvancedRoute: AppSettingsAdvancedRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppWebhooksWebhookIdRouteChildren {
  AppWebhooksWebhookIdEditRoute: typeof AppWebhooksWebhookIdEditRoute
}

const AppWebhooksWebhookIdRouteChildren: AppWebhooksWebhookIdRouteChildren = {
  AppWebhooksWebhookIdEditRoute: AppWebhooksWebhookIdEditRoute,
}

const AppWebhooksWebhookIdRouteWithChildren =
  AppWebhooksWebhookIdRoute._addFileChildren(AppWebhooksWebhookIdRouteChildren)

interface AppRouteChildren {
  AppChannelsRoute: typeof AppChannelsRoute
  AppKeysRoute: typeof AppKeysRoute
  AppPublishRoute: typeof AppPublishRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppInboxMessageIdRoute: typeof AppInboxMessageIdRoute
  AppWebhooksWebhookIdRoute: typeof AppWebhooksWebhookIdRouteWithChildren
  AppWebhooksNewRoute: typeof AppWebhooksNewRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
  AppWebhooksIndexRoute: typeof AppWebhooksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChannelsRoute: AppChannelsRoute,
  AppKeysRoute: AppKeysRoute,
  AppPublishRoute: AppPublishRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppInboxMessageIdRoute: AppInboxMessageIdRoute,
  AppWebhooksWebhookIdRoute: AppWebhooksWebhookIdRouteWithChildren,
  AppWebhooksNewRoute: AppWebhooksNewRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
  AppWebhooksIndexRoute: AppWebhooksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  AppRoute: AppRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  CliRoute: CliRoute,
  DashboardRoute: DashboardRoute,
  MobileRoute: MobileRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
